language: php

sudo: false

php:
- 7.0

env:
- WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.0
      env: SNIFF=1

before_install:
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  # Install PHP CodeSniffer.
  - if [[ "$SNIFF" == "1" ]]; then mkdir -p $PHPCS_DIR && git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR; fi
  # Install WordPress Coding Standards.
  - if [[ "$SNIFF" == "1" ]]; then mkdir -p $SNIFFS_DIR && git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR; fi
  # Set install path for WordPress Coding Standards.
  - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR; fi
  # After CodeSniffer install you should refresh your path.
  - if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi

before_script:
  - if [[ "$SNIFF" != "1" ]]; then bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION; fi

script:
  - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p . --standard=phpcs.xml --runtime-set ignore_warnings_on_exit 1; fi
  - if [[ "$SNIFF" != "1" ]]; phpunit; fi

notifications:
  slack:
    rooms:
      secure: WWTF/9cjGU2CHjA3NavXT2MFsXeaE8qxMUU0XOHknpJOY1iZEa365YHrX6GiYyuQsiwbHWsS7kdYv/k2ikmNYwaU+qL781k9oQ5jh2NsQcfJ1QW0yaIl+h1VI3emZ+2OWx5rZR8qRW0qRe3LeXl31o98M1w+xUG2LCBMCMjkuHAFiX200SmUSyyG1/t43QquwebbO8oNLh37PLE1ky2ZZusXXd+vutpqX4m6d0u8jGV51Aj5H54s+PpXKbhK6VjqsRNTTZ0ivzDuFrp8hlSLj3LjvTq8Sp7E2BI484Lt9/alvVqc5B9yBp7bp7c5zk8kexLTNK+PeUHGSRksXwzHgKLHsZBHWECJk5cCssfMA3zM+mCsJwti+5QiYjuXMj6TE7d5aj/kvOInRad8sobcLxmG4v3htd1XOLnqV79zfQgkF3p6xiav/0WxSv8qeuP1fNdwf2hMeDGd0/NYd8SouwFAkhGKxbr1kFtlJkU2pvT3IywfUXMFCehO4rofJ+eIz45bVbOytdrjbP3MbgjGk6xQY0tqUHjvrGiur2BhH3OAO2MMTYagPkFApA+W52KXyCpfI3EQA7oAYMF/O4C7xN3jRl7Mbxxb4xHacOZwu21y8iAndlCmGxVAu+hppu6a3+1dCKL5sR+y0XsnwMn2i1YdC/cpsCe+cNAxgjQ4Cg8=
